language: go
go:
  - "1.14.x"

before_install:
  - go get github.com/gookit/color
  - go get github.com/rakyll/gotest
  - go get github.com/getkin/kin-openapi/openapi3
  - go get github.com/xeipuuv/gojsonschema
  - go get github.com/stretchr/testify/assert

script:
  - run/citest
  - go build src/main/*.go