language: go
go:
  - "1.4.x"
  - "1.5.x"
  - "1.6.x"
  - "1.7.x"
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
before_install:
  - go get github.com/gookit/color
  - go get github.com/gookit/gotest
  - go get github.com/getkin/kin-openapi
  - go get github.com/xeipuuv/gojsonschema
  - go get github.com/stretchr/testify/assert
script:
  - gotest
  - go build src/main/*.go